import { FieldType, hasFlag, RecordType, UseEdit } from './record.js';

/*
 * App Designer's Build > Create Table, as a script for Oracle: generated,
 * never run. The column rules are read off HRDMO's built tables (every SQL
 * Table's PSRECFIELDDB fields against ALL_TAB_COLUMNS):
 *
 *   Character, Image Reference   VARCHAR2(LENGTH CHAR) NOT NULL (175,713 of 175,713)
 *   Long Character               VARCHAR2(LENGTH CHAR) up to 1,333 characters
 *                                (4,000 bytes in a Unicode database: 221 of 221),
 *                                else CLOB (175 of 175); BLOB when its format is
 *                                Raw Binary (7)
 *   Number, no decimals          up to 9 digits NUMBER(*,0) (INTEGER), else NUMBER(LENGTH)
 *                                (older tables built length 10 as INTEGER too: 1,598 of 4,554)
 *   Signed, no decimals          up to 11 positions NUMBER(*,0), else NUMBER(LENGTH-1)
 *   Number / Signed, decimals    NUMBER(LENGTH-1, DECIMALPOS) / NUMBER(LENGTH-2, DECIMALPOS)
 *                                (8,083 / 12,338: the point, and the sign, count in LENGTH)
 *   Date                         DATE
 *   Time, DateTime               TIMESTAMP(6)
 *   Image                        BLOB
 *
 *   NOT NULL: always for Character, Image Reference and numbers; for Long,
 *   Date, Time and DateTime exactly when the field is Required (no
 *   exception across all four).
 *
 * The key index is PS_<RECORD> on the keys and duplicate order keys in field
 * order, DESC where descending, UNIQUE unless a key is a duplicate order key.
 * Storage clauses (App Designer's DDL model parameters) are not produced.
 */

export interface DdlField {
  name: string;
  type: FieldType;
  length: number;
  decimalPositions: number;
  format?: number;
  useEdit: number;
}

export interface DdlRecord {
  name: string;
  recordType: RecordType;
  /** PSRECDEFN.SQLTABLENAME; blank for the default PS_<RECORD>. */
  sqlTableName: string;
  /** PSRECTBLSPC.DDLSPACENAME. */
  tablespace?: string;
  fields: DdlField[];
}

export function tableName(r: { name: string; sqlTableName: string }): string {
  return r.sqlTableName.trim() || `PS_${r.name}`;
}

export function columnType(f: DdlField): string {
  switch (f.type) {
    case FieldType.Character:
    case FieldType.ImageReference:
      return `VARCHAR2(${f.length} CHAR)`;
    case FieldType.LongCharacter:
      if (f.format === 7) return 'BLOB';
      return f.length > 0 && f.length <= 1333 ? `VARCHAR2(${f.length} CHAR)` : 'CLOB';
    case FieldType.Number:
      if (f.decimalPositions > 0) return `NUMBER(${f.length - 1},${f.decimalPositions})`;
      return f.length <= 9 ? 'NUMBER(*,0)' : `NUMBER(${f.length})`;
    case FieldType.SignedNumber:
      if (f.decimalPositions > 0) return `NUMBER(${f.length - 2},${f.decimalPositions})`;
      return f.length <= 11 ? 'NUMBER(*,0)' : `NUMBER(${f.length - 1})`;
    case FieldType.Date:
      return 'DATE';
    case FieldType.Time:
    case FieldType.DateTime:
      return 'TIMESTAMP(6)';
    case FieldType.Image:
      return 'BLOB';
    default:
      throw new Error(`Field type ${f.type} has no column rule.`);
  }
}

export function notNull(f: DdlField): boolean {
  switch (f.type) {
    case FieldType.LongCharacter:
    case FieldType.Date:
    case FieldType.Time:
    case FieldType.DateTime:
    case FieldType.Image:
      return hasFlag(f.useEdit, UseEdit.Required);
    default:
      return true;
  }
}

/** The Create Table script, or the reason there is none. */
export function createTableScript(r: DdlRecord): string {
  if (r.recordType !== RecordType.Table) {
    throw new Error(`${r.name} is not an SQL Table: only SQL Tables have a Create Table script here.`);
  }
  const table = tableName(r);
  const width = Math.max(...r.fields.map((f) => f.name.length));
  const columns = r.fields.map((f) => `   ${f.name.padEnd(width)} ${columnType(f)}${notNull(f) ? ' NOT NULL' : ''}`);
  const out = [
    `-- ${table}: generated by PeopleSoft Studio from the record definition, not run.`,
    '-- Storage clauses from the DDL model are not included; compare with App Designer\'s build script.',
    `CREATE TABLE ${table} (`,
    columns.join(',\n'),
    `)${r.tablespace ? ` TABLESPACE ${r.tablespace}` : ''}`,
    '/'
  ];
  const keys = r.fields.filter((f) => hasFlag(f.useEdit, UseEdit.Key) || hasFlag(f.useEdit, UseEdit.DuplicateOrderKey));
  if (keys.length > 0) {
    const unique = !keys.some((k) => hasFlag(k.useEdit, UseEdit.DuplicateOrderKey));
    const cols = keys.map((k) => `${k.name}${hasFlag(k.useEdit, UseEdit.DescendingKey) ? ' DESC' : ''}`).join(',\n   ');
    out.push(`CREATE ${unique ? 'UNIQUE ' : ''}INDEX ${table} ON ${table} (\n   ${cols})`, '/');
  }
  return out.join('\n') + '\n';
}
