// Generates docs/unmapped-opcodes.md: for each opcode in a target list, every
// corpus program that still has it unmapped, sorted by that program's total
// unmapped-opcode count (ascending) so the most hand-walkable candidates
// (fewest other opcodes obscuring the real source) sort first.
import { readFileSync, writeFileSync } from 'node:fs';
import { decodeProgram } from '../dist-test/peoplecode/decoder.js';
import { NameTable } from '../dist-test/peoplecode/progtext.js';

const corpus = JSON.parse(readFileSync(process.argv[2], 'utf8'));
const OUT = process.argv[3];
const TARGETS = [0x00, 0x20, 0x6e, 0x70, 0x6f, 0x73, 0x74, 0x72, 0x6c];

function namesOf(e) {
  const t = new NameTable();
  for (const [num, name] of e.names) t.add(num, name);
  return t;
}

const byOpcode = new Map(TARGETS.map((op) => [op, []]));

for (const e of corpus) {
  const buf = Buffer.from(e.bytes, 'base64');
  const isAppClass = e.key.type === 58;
  const result = decodeProgram(buf, namesOf(e), { mode: 'auto', isApplicationClass: isAppClass });
  const total = result.unknownOpcodes.length;
  const counts = new Map();
  for (const u of result.unknownOpcodes) counts.set(u.opcode, (counts.get(u.opcode) ?? 0) + 1);
  for (const op of TARGETS) {
    const count = counts.get(op);
    if (!count) continue;
    byOpcode.get(op).push({
      name: e.key.parts.join('.'), type: e.key.type, bytes: buf.length,
      count, totalUnmapped: total
    });
  }
}

const lines = [];
lines.push('# Unmapped opcode tracker');
lines.push('');
lines.push('Generated by `scripts/track-opcodes.mjs` against the calibration corpus.');
lines.push('Not narrative (see `docs/ROADMAP.md` for that) -- a working list of which');
lines.push('real programs still carry each of these opcodes unmapped, so the next');
lines.push('investigation pass has real byte-for-byte samples to start from instead of');
lines.push('re-running `corpus-analyze.mjs` from scratch. Regenerate after any decoder');
lines.push('change: `node scripts/track-opcodes.mjs <corpus.json> docs/unmapped-opcodes.md`.');
lines.push('');
lines.push('Each program is sorted by its own total unmapped-opcode count (ascending) --');
lines.push('the programs at the top of each list are the best hand-walking candidates,');
lines.push('since fewer *other* unmapped bytes obscure the real source around this one.');
lines.push('');

for (const op of TARGETS) {
  const progs = byOpcode.get(op).sort((a, b) => a.totalUnmapped - b.totalUnmapped);
  const totalOccurrences = progs.reduce((s, p) => s + p.count, 0);
  lines.push(`## 0x${op.toString(16).padStart(2, '0')}`);
  lines.push('');
  lines.push(`${progs.length} programs, ${totalOccurrences} occurrences total.`);
  lines.push('');
  if (progs.length === 0) {
    lines.push('(none)');
  } else {
    lines.push('| program | type | bytes | this opcode | total unmapped |');
    lines.push('|---|---|---|---|---|');
    for (const p of progs) {
      lines.push(`| ${p.name} | ${p.type === 58 ? 'App Class' : 'Function'} | ${p.bytes} | ${p.count} | ${p.totalUnmapped} |`);
    }
  }
  lines.push('');
}

writeFileSync(OUT, lines.join('\n'));
console.log(`wrote ${OUT}`);
for (const op of TARGETS) {
  console.log(`  0x${op.toString(16).padStart(2, '0')}: ${byOpcode.get(op).length} programs`);
}
