/**
 * Cycle 15: reverse-engineer ordinary-statement blank-line preservation
 * inside Application Class method bodies. Read-only, no encoder changes.
 *
 * Core hypothesis under test (already documented, pre-existing evidence
 * in encoder.ts's own `leadingLocalRun`/`hasCompiledReferences` comments,
 * and independently reproduced this cycle via matched-control
 * `encodeFragment` tests -- see the Cycle 15 report):
 *
 *   Blank-line/inter-statement `0x4F` markers (and the declaration-
 *   section-closing `0x2D`) are flushed from a DEFERRED buffer only if
 *   the CURRENT COMPILATION UNIT (one `encodeFragmentInternal` call) has
 *   AT LEAST ONE compiled PSPCMNAME reference beyond the blank owner
 *   placeholder. A "primitive-only" unit (no Record/Field/Scroll/
 *   PACKAGE/etc. reference anywhere) drops ALL such markers; a
 *   "reference-bearing" unit keeps them all.
 *
 * Cycle 14 encodes each Application Class method body as its OWN,
 * independent `encodeFragmentInternal` call. This script tests whether
 * that per-method scoping (rather than a whole-class/whole-program
 * scoping) explains the byte mismatches Cycle 14 left unresolved, by
 * checking, per method, in ISOLATION, whether it has any compiled
 * reference of its own, and correlating that against where each
 * definition's first real byte difference actually falls.
 *
 * Usage:
 *   npx tsx tools/corpus/research/appclass-blankline-boundary-analysis.ts
 */

import {
  parseApplicationClassSource,
  type ApplicationClassMethodMember
} from '../../../src/peoplecode/applicationClassProgram';
import { encodeProgram, encodeProgramArtifacts } from '../../../src/peoplecode/encoder';
import { listSnapshotDefinitions } from '../snapshot/reader';
import { openSnapshotDatabase } from '../snapshot/store';
import type { SnapshotDefinition } from '../snapshot/types';

const APPLICATION_CLASS_OBJECT_ID = 104;

function ownerPackagePath(definition: SnapshotDefinition): string[] {
  const values = [
    definition.objectvalue1, definition.objectvalue2, definition.objectvalue3,
    definition.objectvalue4, definition.objectvalue5, definition.objectvalue6,
    definition.objectvalue7
  ].map(value => value.trim());
  const onExecute = values.findIndex(value => value.toLowerCase() === 'onexecute');
  return values.slice(0, onExecute < 0 ? values.length : onExecute).filter(Boolean);
}

/** Whether an ISOLATED encode of this exact text produces any compiled
 * reference beyond the blank owner placeholder -- the precise
 * `hasCompiledReferences` condition, measured via the real encoder
 * itself (not approximated by a source-text heuristic). */
function hasCompiledReferences(body: string): boolean {
  const completed = /;\s*$/.test(body) ? body : `${body};`;
  try {
    const { references } = encodeProgramArtifacts(completed);
    return (
      references.length > 1 ||
      references[0]?.recordName !== undefined ||
      references[0]?.fieldName !== undefined
    );
  } catch {
    return false;
  }
}

interface MethodByteRange {
  member: ApplicationClassMethodMember;
  start: number;
  end: number;
}

/** Locates each method's own implementation-header start (`63 41 <UTF16LE
 * name>`) inside the GENERATED bytes, in physical (implementationOrder)
 * order, giving each method an approximate byte range within the
 * generated statements section. */
function locateMethodByteRanges(
  generated: Buffer,
  methods: readonly ApplicationClassMethodMember[]
): MethodByteRange[] {
  const byImplementationOrder = [...methods].sort((a, b) => a.implementationOrder - b.implementationOrder);
  const starts: number[] = [];
  let searchFrom = 0;
  for (const member of byImplementationOrder) {
    // The implementation header is `63 41 <text-operand introducer byte>
    // <UTF16LE name>` -- a one-byte length/kind introducer sits between
    // `0x41` and the name itself (confirmed directly: offset 247 in
    // definition 28994 reads `15 2d 4f 63 41 0a 43 00 6f 00 ...`). Search
    // for the marker prefix `63 41` followed by the name within a few
    // bytes, rather than assuming the introducer byte's exact value.
    const namePrefix = Buffer.from(`${member.name}`, 'utf16le');
    let at = -1;
    let cursor = searchFrom;
    while (true) {
      const nameAt = generated.indexOf(namePrefix, cursor);
      if (nameAt < 0) break;
      const precedingWindow = generated.subarray(Math.max(0, nameAt - 4), nameAt);
      if (precedingWindow.includes(0x41) && precedingWindow.includes(0x63)) {
        at = nameAt - 3; // back up to include `63 41 <introducer>`
        break;
      }
      cursor = nameAt + 1;
    }
    starts.push(at);
    if (at >= 0) searchFrom = at + 3 + namePrefix.length;
  }
  return byImplementationOrder.map((member, index) => ({
    member,
    start: starts[index],
    end: index + 1 < starts.length ? starts[index + 1] : generated.length
  }));
}

function firstDiffOffset(a: Buffer, b: Buffer): number | undefined {
  const length = Math.min(a.length, b.length);
  for (let i = 0; i < length; i++) {
    if (a[i] !== b[i]) return i;
  }
  return a.length === b.length ? undefined : length;
}

function countBy<T>(values: readonly T[], key: (value: T) => string): Record<string, number> {
  const result: Record<string, number> = {};
  for (const value of values) {
    const k = key(value);
    result[k] = (result[k] ?? 0) + 1;
  }
  return Object.fromEntries(Object.entries(result).sort((a, b) => b[1] - a[1]));
}

function main(): void {
  const db = openSnapshotDatabase();
  const definitions = listSnapshotDefinitions(db).filter(definition => definition.objectid1 === APPLICATION_CLASS_OBJECT_ID);
  db.close();

  const target = definitions
    .map(definition => ({ definition, parsed: parseApplicationClassSource(definition.sourceText) }))
    .filter((item): item is { definition: SnapshotDefinition; parsed: NonNullable<ReturnType<typeof parseApplicationClassSource>> } =>
      item.parsed !== undefined &&
      item.parsed.extendsType === undefined &&
      item.parsed.implementsType === undefined &&
      item.parsed.members.every(member => member.kind === 'method')
    );

  console.log(`Target population (methods-only Application Class): ${target.length}`);

  let exact = 0;
  let mismatch = 0;
  let errors = 0;
  const errorMessages: string[] = [];

  const boundaryCases: Array<{
    id: number;
    firstDiff: number;
    methodIndex: number;
    methodName: string;
    methodHasOwnReferences: boolean;
    methodImplementationOrder: number;
    methodCount: number;
    offsetIntoMethod: number;
    methodByteLength: number;
  }> = [];

  const perMethodReferenceStats = { withRefs: 0, withoutRefs: 0 };
  const definitionsAllMethodsHaveRefs = { all: 0, some: 0, none: 0 };

  for (const { definition, parsed } of target) {
    const methods = parsed.members as ApplicationClassMethodMember[];
    const methodRefFlags = methods.map(member => ({ member, hasRefs: hasCompiledReferences(member.body) }));
    for (const { hasRefs } of methodRefFlags) {
      if (hasRefs) perMethodReferenceStats.withRefs++;
      else perMethodReferenceStats.withoutRefs++;
    }
    const withRefsCount = methodRefFlags.filter(item => item.hasRefs).length;
    if (withRefsCount === methodRefFlags.length) definitionsAllMethodsHaveRefs.all++;
    else if (withRefsCount === 0) definitionsAllMethodsHaveRefs.none++;
    else definitionsAllMethodsHaveRefs.some++;

    const path = ownerPackagePath(definition);
    let generated: Buffer;
    try {
      generated = encodeProgram(definition.sourceText, {
        owner: { recordName: path[0] ?? '', fieldName: path[1] ?? '', packagePath: path }
      });
    } catch (error) {
      errors++;
      errorMessages.push(error instanceof Error ? error.message : String(error));
      continue;
    }

    if (generated.equals(definition.storedProgram)) {
      exact++;
      continue;
    }
    mismatch++;

    // The 37-byte header encodes each buffer's OWN total statement/name/
    // slot lengths, so it trivially "differs" as soon as anything later
    // diverges (they end up different total sizes) -- not a meaningful
    // boundary in its own right. Compare from byte 37 onward only.
    const diffOffsetPastHeader = firstDiffOffset(
      generated.subarray(37),
      definition.storedProgram.subarray(37)
    );
    if (diffOffsetPastHeader === undefined) continue;
    const diffOffset = diffOffsetPastHeader + 37;

    const ranges = locateMethodByteRanges(generated, methods);
    const containing = ranges.findIndex(range => range.start >= 0 && diffOffset >= range.start && diffOffset < range.end);
    if (containing < 0) continue;

    const range = ranges[containing];
    const refInfo = methodRefFlags.find(item => item.member === range.member);
    boundaryCases.push({
      id: definition.definitionId,
      firstDiff: diffOffset,
      methodIndex: containing,
      methodName: range.member.name,
      methodHasOwnReferences: refInfo?.hasRefs ?? false,
      methodImplementationOrder: range.member.implementationOrder,
      methodCount: methods.length,
      offsetIntoMethod: diffOffset - range.start,
      methodByteLength: range.end - range.start
    });
  }

  console.log(JSON.stringify({
    population: { target: target.length, exact, mismatch, errors },
    perMethodReferenceStats,
    definitionsAllMethodsHaveRefs,
    boundaryCasesLocated: boundaryCases.length,
    mismatchesWithoutLocatedBoundary: mismatch - boundaryCases.length,
    boundaryCasesByMethodHasOwnReferences: countBy(boundaryCases, c => c.methodHasOwnReferences ? 'has-own-references' : 'no-own-references'),
    boundaryCasesByMethodPositionInDefinition: countBy(boundaryCases, c => `method ${c.methodImplementationOrder + 1} of ${c.methodCount}`),
    errorMessageTop: countBy(errorMessages, message => message.replace(/offset \d+/, 'offset N')),
    sampleBoundaryCases: boundaryCases.slice(0, 25)
  }, null, 2));
}

main();
