/*
 * Cycle 83: token-level first-divergence extract for every NONEXACT
 * definition (research only, no encoder/decoder changes).
 *
 * The Cycle 73 taxonomy reports only the FIRST index where the stored and
 * generated PSPCMNAME key lists differ. That cannot tell a missing row from
 * an extra one, nor whether the program would be EXACT once the reference
 * stream is corrected. This extract decodes BOTH the stored and the
 * generated PSPCMPROG and maps every name operand (0x21/0x4A/0x48) to its
 * RECNAME.REFNAME identity (stored names for stored bytes, generated
 * references for generated bytes). Comparing the two token streams by
 * identity then separates:
 *
 *   - identical token identities, different NAMENUMs -> reference
 *     allocation only (fixing allocation alone would give EXACT);
 *   - a differing operand identity -> wrong operand identity;
 *   - non-operand token/format differences -> structural / token / trivia;
 *   - identical tokens and NAMENUMs but different bytes -> header/trailer.
 *
 * Owner context matches `validator.ts` (OBJECTID-located RECNAME/FIELDNAME;
 * package path before `OnExecute`). Decoding uses the same
 * `isApplicationClass` (OBJECTID1 = 104) flag as the validator.
 *
 * Input:  .claude/nonexact-taxonomy.json (fresh run of cycle73 taxonomy)
 * Output: JSON lines, one row per NONEXACT definition (--out path).
 *
 * Usage: npx tsx tools/corpus/research/cycle83-token-divergence-extract.ts --out <file.jsonl>
 */
import fs from 'node:fs';
import path from 'node:path';

import { openSnapshotDatabase } from '../snapshot/store';
import { listSnapshotDefinitions } from '../snapshot/reader';
import { encodeProgramArtifacts } from '../../../src/peoplecode/encoder';
import { decodeProgram } from '../../../src/peoplecode/decoder';
import { NameTable } from '../../../src/peoplecode/progtext';

function ownerContextOf(def: any) {
  const values = [def.objectvalue1, def.objectvalue2, def.objectvalue3, def.objectvalue4, def.objectvalue5, def.objectvalue6, def.objectvalue7]
    .map((v: string) => (v ?? '').trim());
  const ids = [def.objectid1, def.objectid2, def.objectid3, def.objectid4, def.objectid5, def.objectid6, def.objectid7];
  const eventIndex = values.findIndex((v: string) => v.toLowerCase() === 'onexecute');
  const recordIndex = ids.findIndex(id => id === 1);
  const fieldIndex = ids.findIndex(id => id === 2);
  return {
    recordName: recordIndex >= 0 ? values[recordIndex] : values[0],
    fieldName: fieldIndex >= 0 ? values[fieldIndex] : values[1],
    packagePath: values.slice(0, eventIndex < 0 ? values.length : eventIndex).filter(Boolean)
  };
}

function storedKeyOf(row: any): string {
  return `${String(row.recname ?? '').trim().toUpperCase()}.${String(row.refname ?? '').trim().toUpperCase()}`;
}

/** Same RECNAME.REFNAME mapping as the Cycle 73 taxonomy's `gKeyOf`. */
function generatedKeyOf(g: any): string {
  switch (g.kind) {
    case 'owner':
      return (g.recordName || g.fieldName)
        ? `${(g.recordName ?? '').toUpperCase()}.${(g.fieldName ?? '').toUpperCase()}`
        : '.';
    case 'package': return `PACKAGE.${(g.packageName ?? '').toUpperCase()}`;
    case 'scroll': return `SCROLL.${(g.recordName ?? '').toUpperCase()}`;
    case 'record': return `RECORD.${(g.recordName ?? '').toUpperCase()}`;
    case 'field': return `FIELD.${(g.fieldName ?? '').toUpperCase()}`;
    case 'component': return `COMPONENT.${(g.objectName ?? '').toUpperCase()}`;
    default: return `${(g.recordName ?? '').toUpperCase()}.${(g.fieldName ?? '').toUpperCase()}`;
  }
}

function tokenSignatures(bytes: Buffer, keyByNameNum: Map<number, string>, isApplicationClass: boolean) {
  const names = new NameTable();
  for (const [nameNum, key] of keyByNameNum) names.add(nameNum, key);
  const decoded = decodeProgram(bytes, names, { mode: 'auto', isApplicationClass });
  const sig: string[] = [];
  const fmt: number[] = [];
  const nameNums: (number | null)[] = [];
  for (const token of decoded.tokens) {
    if (token.nameNum !== undefined) {
      sig.push(`N${token.opcode.toString(16)}:${keyByNameNum.get(token.nameNum) ?? `?${token.nameNum}`}`);
      nameNums.push(token.nameNum);
    } else {
      sig.push(`${token.opcode.toString(16)}:${String(token.text ?? '').slice(0, 48)}`);
      nameNums.push(null);
    }
    fmt.push(token.format);
  }
  return { sig, fmt, nameNums };
}

function main(): void {
  const outIndex = process.argv.indexOf('--out');
  if (outIndex < 0) throw new Error('--out <file.jsonl> is required');
  const outPath = process.argv[outIndex + 1];

  const taxonomy = JSON.parse(fs.readFileSync(path.join(__dirname, '../../../.claude/nonexact-taxonomy.json'), 'utf8'));
  const rowsById = new Map<number, any>(taxonomy.rows.map((r: any) => [r.definitionId, r]));

  const db = openSnapshotDatabase();
  const out = fs.openSync(outPath, 'w');
  let processed = 0;
  for (const def of listSnapshotDefinitions(db) as any[]) {
    const tax = rowsById.get(def.definitionId);
    if (tax === undefined) continue;
    processed++;
    const isApplicationClass = def.objectid1 === 104;
    const row: any = {
      id: def.definitionId,
      display: def.displayName,
      objectid1: def.objectid1,
      cat: tax.primaryCategory,
      cls: tax.classification,
      fwdExact: tax.sourceEncodeExact,
      rtExact: tax.roundtripExact,
      err: tax.errorMessage,
      construct: tax.construct
    };

    const storedKeys = new Map<number, string>();
    for (const r of def.names) storedKeys.set(Number(r.namenum), storedKeyOf(r));
    row.storedKeys = [...storedKeys.values()];

    let generated: { program: Buffer; references: any[] } | undefined;
    try {
      generated = encodeProgramArtifacts(def.sourceText, { owner: ownerContextOf(def) } as any) as any;
    } catch (error) {
      row.encodeError = error instanceof Error ? error.message : String(error);
    }

    if (generated !== undefined) {
      const generatedKeys = new Map<number, string>();
      for (const r of generated.references) generatedKeys.set(r.sequence, generatedKeyOf(r));
      row.generatedKeys = [...generatedKeys.values()];
      row.storedLength = def.storedProgram.length;
      row.generatedLength = generated.program.length;
      try {
        const s = tokenSignatures(def.storedProgram, storedKeys, isApplicationClass);
        row.sSig = s.sig; row.sFmt = s.fmt; row.sNN = s.nameNums;
      } catch (error) {
        row.storedDecodeError = error instanceof Error ? error.message : String(error);
      }
      try {
        const g = tokenSignatures(generated.program, generatedKeys, isApplicationClass);
        row.gSig = g.sig; row.gFmt = g.fmt; row.gNN = g.nameNums;
      } catch (error) {
        row.generatedDecodeError = error instanceof Error ? error.message : String(error);
      }
    }
    fs.writeSync(out, JSON.stringify(row) + '\n');
    if (processed % 500 === 0) console.log(`  ...${processed}`);
  }
  fs.closeSync(out);
  db.close();
  console.log(`Wrote ${processed} rows to ${outPath}`);
}

main();
