/*
 * Cycle 93: per-definition PSPCMNAME list snapshot for before/after
 * comparison of an encoder change (research only).
 *
 * Forward-exact bytes alone hide reference mistakes: PACKAGE rows are never
 * operands, so a missing row and an extra row can cancel (a compensating
 * error) and leave PSPCMPROG byte-identical. This sweep records, for every
 * definition, the stored and the generated row lists (PACKAGE rows keep
 * their REFNAME; every other row is collapsed to `o`), whether the
 * generated program is forward-exact, and a hash of the generated bytes.
 *
 * Run it at two encoder states and compare with
 * `cycle93-names-distance-compare.py`: a rule is contradiction-free when no
 * changed definition's generated list moves FARTHER from the stored list.
 *
 * Usage: npx tsx tools/corpus/research/cycle93-names-distance-sweep.ts <out.json>
 */
import fs from 'node:fs';
import { createHash } from 'node:crypto';

import { openSnapshotDatabase } from '../snapshot/store';
import { listSnapshotDefinitions } from '../snapshot/reader';
import { encodeProgramArtifacts } from '../../../src/peoplecode/encoder';

function ownerOf(def: any) {
  const values = [def.objectvalue1, def.objectvalue2, def.objectvalue3, def.objectvalue4, def.objectvalue5, def.objectvalue6, def.objectvalue7]
    .map((v: string) => (v ?? '').trim());
  const ids = [def.objectid1, def.objectid2, def.objectid3, def.objectid4, def.objectid5, def.objectid6, def.objectid7];
  const eventIndex = values.findIndex((v: string) => v.toLowerCase() === 'onexecute');
  const recordIndex = ids.findIndex(id => id === 1);
  const fieldIndex = ids.findIndex(id => id === 2);
  return {
    recordName: recordIndex >= 0 ? values[recordIndex] : values[0],
    fieldName: fieldIndex >= 0 ? values[fieldIndex] : values[1],
    packagePath: values.slice(0, eventIndex < 0 ? values.length : eventIndex).filter(Boolean)
  };
}

const out: Record<number, { s: string[]; g: string[]; x: boolean; h: string; d: boolean }> = {};
for (const def of listSnapshotDefinitions(openSnapshotDatabase()) as any[]) {
  const rows = [...def.names].sort((a: any, b: any) => Number(a.namenum) - Number(b.namenum));
  const stored = rows
    .map((r: any) => String(r.recname ?? '').trim().toUpperCase() === 'PACKAGE' ? `PACKAGE.${String(r.refname ?? '').trim().toUpperCase()}` : 'o')
    .slice(1);
  const descriptive = rows.some((r: any) => String(r.recname ?? '').trim().toUpperCase() === 'PACKAGE' && String(r.packageroot ?? '').trim() !== '');
  try {
    const artifacts = encodeProgramArtifacts(def.sourceText, { owner: ownerOf(def) } as any) as any;
    const generated = artifacts.references
      .map((r: any) => r.kind === 'package' ? `PACKAGE.${String(r.packageName ?? '').toUpperCase()}` : 'o')
      .slice(1);
    out[def.definitionId] = {
      s: stored,
      g: generated,
      x: artifacts.program.equals(def.storedProgram),
      h: createHash('sha1').update(artifacts.program).digest('hex'),
      d: descriptive
    };
  } catch {
    // unsupported syntax / encode error: not part of a reference comparison
  }
}
fs.writeFileSync(process.argv[2], JSON.stringify(out));
const values = Object.values(out);
console.log(`${values.length} encoded, ${values.filter(v => v.x).length} forward-exact`);
