/*
 * Cycle 163: COMPLETE_DOWNSTREAM byte differences and the ordinary
 * singleton tail (research only).
 *
 * Sections (all by default, or one with `--section <name>`):
 *   first      each listed program (`--ids a,b`; default the
 *              COMPLETE_DOWNSTREAM rows of the taxonomy): reference-list
 *              equality and the first decoded-token difference with its
 *              byte neighbourhood (16 before / 32 after);
 *   layout     the layout shapes behind them: App Class headers with a
 *              `&Public` / `&Private` / `&Protected` parameter, a bare
 *              `Returns array` Function header, a trailing comma in a
 *              declaration list, Application Class definitions with no
 *              class, interfaces by `end-interface` terminator;
 *   funclocal  uses of a variable outside the ordinary Function whose
 *              `Local` is its only declaration, by chain shape.
 *
 * Usage:
 *   npx tsx tools/corpus/research/cycle163-downstream-census.ts --taxonomy t.json [--section <name>] [--ids 1,2]
 */
import fs from 'node:fs';

import { maskNonCode, parseApplicationClassSource } from '../../../src/peoplecode/applicationClassProgram';
import {
  openHarnessContext, encodeAsHarness, isApplicationClass, storedReferenceKeys, generatedReferenceKey,
  storedNameTable, generatedNameTable, decodeAsHarness
} from './lib/harnessContext';

const args = process.argv.slice(2);
const taxonomyRows: any[] = args[0] === '--taxonomy' ? JSON.parse(fs.readFileSync(args[1], 'utf8')).rows : [];
const nonexact = new Set<number>(taxonomyRows.map(r => r.definitionId));
const option = (name: string) => { const i = args.indexOf(name); return i >= 0 ? args[i + 1] : undefined; };
const only = option('--section');
const run = (name: string) => only === undefined || only === name;
const ctx = openHarnessContext();
const tally = new Map<string, Set<number>[]>();
const add = (key: string, id: number) => { const v = tally.get(key) ?? [new Set(), new Set()]; tally.set(key, v); v[nonexact.has(id) ? 1 : 0].add(id); };
const flush = (title: string) => {
  console.log(`== ${title}`);
  for (const [k, [exact, non]] of [...tally].sort()) console.log(`  ${k.padEnd(56)} EXACT ${String(exact.size).padStart(4)}  non ${String(non.size).padStart(3)}  e.g. ${[...exact].slice(0, 4).join(' ')}${non.size ? ` | non ${[...non].slice(0, 10).join(' ')}` : ''}`);
  tally.clear();
};

if (run('first')) {
  const ids = option('--ids')?.split(',').map(Number) ?? taxonomyRows.filter(r => r.primaryCategory === 'REFERENCE_COMPLETE_DOWNSTREAM').map(r => r.definitionId);
  console.log('== first: list equality and first decoded-token difference');
  for (const id of ids) {
    const def = ctx.definitions.find(d => d.definitionId === id)! as any;
    const r = encodeAsHarness(ctx, def); if (!r.artifacts) { console.log(`  ${id} encode error`); continue; }
    const s = storedReferenceKeys(def), g = r.artifacts.references.map(generatedReferenceKey);
    const listEqual = s.length === g.length && s.every((k, i) => k === g[i]);
    const st = decodeAsHarness(def, def.storedProgram, storedNameTable(def)).tokens as any[];
    const gt = decodeAsHarness(def, r.artifacts.program, generatedNameTable(r.artifacts.references)).tokens as any[];
    let k = 0;
    while (k < Math.min(st.length, gt.length) && st[k].opcode === gt[k].opcode && (st[k].text ?? '') === (gt[k].text ?? '') && (st[k].nameNum ?? -1) === (gt[k].nameNum ?? -1)) k++;
    const show = (t: any[]) => t.slice(Math.max(0, k - 3), k + 4).map(x => `${x.opcode.toString(16)}${x.text !== undefined ? `:${JSON.stringify(String(x.text).slice(0, 20))}` : ''}`).join(' ');
    console.log(`  ${id} ${isApplicationClass(def) ? 'App Class' : 'ordinary'}${r.fallback ? ' (fallback)' : ''} list ${listEqual ? 'equal' : `differs ${s.length}/${g.length}`} bytes ${def.storedProgram.length}/${r.artifacts.program.length} first token difference ${k} of ${st.length}/${gt.length}`);
    console.log(`    stored    ${show(st)}`);
    console.log(`    generated ${show(gt)}`);
    const offset = st[k]?.offset ?? gt[k]?.offset;
    if (offset !== undefined) {
      console.log(`    stored bytes    ${def.storedProgram.subarray(Math.max(0, offset - 16), offset + 32).toString('hex')}`);
      console.log(`    generated bytes ${r.artifacts.program.subarray(Math.max(0, offset - 16), offset + 32).toString('hex')}`);
    }
  }
}

for (const def of ctx.definitions as any[]) {
  const appClass = isApplicationClass(def);
  const code = maskNonCode(def.sourceText);
  if (run('layout')) {
    if (appClass) {
      const parsed = parseApplicationClassSource(def.sourceText);
      if (!parsed) { if (!/\b(?:class|interface)\b/i.test(code)) add('Application Class definition with no class', def.definitionId); }
      else {
        const header = code.slice(parsed.unitStart, parsed.unitEnd);
        if (/&(?:public|private|protected)\b/i.test(header)) add('App Class header parameter named &Public / &Private / &Protected', def.definitionId);
        if (/\binstance\s+[^;]*,\s*;/i.test(header)) add('App Class instance list with trailing comma', def.definitionId);
        if (parsed.unitKind === 'interface') add(`interface ${/end-interface\s*;/i.test(code) ? 'end-interface;' : 'end-interface without ;'}`, def.definitionId);
      }
    }
    if (/\bFunction\s+\w+\s*(?:\([^)]*\))?\s*Returns\s+array\b(?!\s+of\b)/i.test(code)) add(`${appClass ? 'App Class' : 'ordinary'} Function Returns bare array`, def.definitionId);
    if (/\b(?:Local|Global|Component)\s+[\w: ]+?\s+&\w+(?:\s*,\s*&\w+)*\s*,\s*;/i.test(code)) add(`${appClass ? 'App Class' : 'ordinary'} declaration list with trailing comma`, def.definitionId);
  }
  if (run('funclocal') && !appClass) {
    const regions = [...code.matchAll(/(?:^|\n)[ \t]*Function\s+\w+#?[\s\S]*?\bEnd-Function\b/gi)].map(m => ({ start: m.index!, end: m.index! + m[0].length }));
    if (!regions.length) continue;
    const regionAt = (offset: number) => regions.findIndex(r => offset >= r.start && offset < r.end);
    const declared = new Map<string, Set<number>>();
    for (const m of code.matchAll(/\b(Local|Global|Component)\s+(Row|Record|Rowset)\s+(&\w+(?:\s*,\s*&\w+)*)/gi)) {
      const region = /^Local$/i.test(m[1]) ? regionAt(m.index!) : -1;
      for (const name of m[3].split(',')) { const key = name.trim().toLowerCase(); declared.set(key, (declared.get(key) ?? new Set()).add(region)); }
    }
    for (const m of code.matchAll(/\bFunction\s+\w+\s*\(([^)]*)\)/gi)) for (const p of m[1].matchAll(/&\w+/g)) { const key = p[0].toLowerCase(); declared.set(key, (declared.get(key) ?? new Set()).add(regionAt(m.index!))); }
    for (const m of code.matchAll(/(&\w+)\s*\.\s*(\w+)\s*(\()?/g)) {
      const regionsDeclared = declared.get(m[1].toLowerCase()); if (!regionsDeclared || regionsDeclared.has(-1)) continue;
      const here = regionAt(m.index!); if (regionsDeclared.has(here)) continue;
      add(`ordinary Function-local name used ${here < 0 ? 'at top level' : 'in another Function'}: ${m[3] ? 'method call' : 'bare member'}`, def.definitionId);
    }
  }
}
if (run('layout')) flush('layout: downstream layout shapes');
if (run('funclocal')) flush('funclocal: Function-local Row / Record / Rowset names used outside their Function');
