/*
 * Cycle 92: Application-Class-typed Local section continuation census
 * (research only).
 *
 * For every non-App-Class program whose leading region (before the first
 * executable statement) contains an App-Class-typed Local (`La`), walk the
 * leading items from that first `La` on. For every Local item (L / La / Li)
 * whose NEXT item is not a Local, record the kind of that next item -- or,
 * when it is a comment, the kind of the next real item after the comment
 * run -- and whether the stored and generated bytes have a 0x2D at that
 * point.
 *
 * Item kinds (Cycle 85 splitter): L Local, La App-Class Local, Li
 * initialized Local, D Global/Component/Constant/PanelGroup/Declare, I
 * import, F Function definition, C comment, X executable.
 *
 * Usage: npx tsx tools/corpus/research/cycle92-appclass-local-section-census.ts
 */
import { openSnapshotDatabase } from '../snapshot/store';
import { listSnapshotDefinitions } from '../snapshot/reader';
import { encodeProgramArtifacts } from '../../../src/peoplecode/encoder';
import { NameTable } from '../../../src/peoplecode/progtext';
import { topLevelItems } from './cycle85-function-continuity-census';

function ownerContextOf(def: any) {
  const values = [def.objectvalue1, def.objectvalue2, def.objectvalue3, def.objectvalue4, def.objectvalue5, def.objectvalue6, def.objectvalue7]
    .map((v: string) => (v ?? '').trim());
  const ids = [def.objectid1, def.objectid2, def.objectid3, def.objectid4, def.objectid5, def.objectid6, def.objectid7];
  const eventIndex = values.findIndex((v: string) => v.toLowerCase() === 'onexecute');
  const recordIndex = ids.findIndex(id => id === 1);
  const fieldIndex = ids.findIndex(id => id === 2);
  return {
    recordName: recordIndex >= 0 ? values[recordIndex] : values[0],
    fieldName: fieldIndex >= 0 ? values[fieldIndex] : values[1],
    packagePath: values.slice(0, eventIndex < 0 ? values.length : eventIndex).filter(Boolean)
  };
}

const tally = new Map<string, number[]>();
let programs = 0;
for (const def of listSnapshotDefinitions(openSnapshotDatabase()) as any[]) {
  if (def.objectid1 === 104) continue;
  const storedNames = new NameTable();
  for (const r of def.names) storedNames.add(Number(r.namenum), 'x');
  let stored: any[];
  let generated: any[] | undefined;
  try {
    stored = topLevelItems(def.storedProgram, storedNames, false);
  } catch { continue; }
  const firstX = stored.findIndex(i => i.kind === 'X');
  const leadEnd = firstX < 0 ? stored.length : firstX;
  const firstLa = stored.findIndex((i, index) => index < leadEnd && i.kind === 'La');
  if (firstLa < 0) continue;
  programs++;
  try {
    const artifacts = encodeProgramArtifacts(def.sourceText, { owner: ownerContextOf(def) } as any);
    const generatedNames = new NameTable();
    for (const r of artifacts.references) generatedNames.add(r.sequence, 'x');
    generated = topLevelItems(artifacts.program, generatedNames, false);
  } catch { generated = undefined; }
  const aligned = generated !== undefined && generated.length === stored.length &&
    generated.every((g, i) => g.kind === stored[i].kind);
  let sectionClosedInStored = false;
  for (let i = firstLa; i < leadEnd; i++) {
    if (!stored[i].kind.startsWith('L')) continue;
    const next = stored[i + 1]?.kind ?? 'EOF';
    if (next.startsWith('L')) continue;
    // next real item after a comment run
    let j = i + 1;
    while (j < stored.length && stored[j].kind === 'C') j++;
    const nextReal = stored[j]?.kind ?? 'EOF';
    const via = next === 'C' ? 'comment->' : '';
    const runHasInit = (() => { for (let k = i; k >= firstLa && stored[k].kind.startsWith('L'); k--) if (stored[k].kind === 'Li') return true; return false; })();
    const s2d = stored[i].layoutAfter.includes('2D');
    const g2d = aligned ? generated![i].layoutAfter.includes('2D') : undefined;
    const key = `${sectionClosedInStored ? 'after-close ' : 'section-open'} Local -> ${(via + nextReal).padEnd(12)} init=${runHasInit ? 'y' : 'n'} stored2D=${s2d ? 'Y' : 'n'} generated2D=${g2d === undefined ? '?' : g2d ? 'Y' : 'n'} ${g2d === undefined ? 'UNALIGNED' : s2d === g2d ? 'match' : 'MISMATCH'}`;
    (tally.get(key) ?? tally.set(key, []).get(key)!).push(def.definitionId);
    if (s2d) sectionClosedInStored = true;
  }
}
console.log(`programs with an App-Class Local before executable code: ${programs}`);
for (const [key, ids] of [...tally].sort((a, b) => b[1].length - a[1].length)) {
  console.log(String(ids.length).padStart(5), key, [...new Set(ids)].slice(0, 7).join(','));
}
