/*
 * Cycle 107: per-definition PSPCMNAME / byte sweep with the validator's own
 * encode context (owner record, field AND package path), optionally with
 * the snapshot Application Class type-metadata provider (research only).
 *
 *   --provider       pass the provider (its answers are used)
 *   --diagnostics    pass it in diagnostics-only mode (consulted and
 *                    traced, answers not used): bytes must not change
 *
 * Output (same shape as `cycle93-names-distance-sweep.ts`, so
 * `cycle93-names-distance-compare.py` compares two runs): per definition
 * the stored and generated PACKAGE lists (other rows collapsed to `o`),
 * forward-exact, a hash of the generated bytes, plus `t`: the provider
 * consultations (resolved to a class / to another type / unresolved).
 *
 * Usage: npx tsx tools/corpus/research/cycle107-provider-sweep.ts <out.json> [--provider | --diagnostics]
 */
import fs from 'node:fs';
import { createHash } from 'node:crypto';

import { openSnapshotDatabase } from '../snapshot/store';
import { listSnapshotDefinitions } from '../snapshot/reader';
import { listSnapshotApplicationClassDefinitions } from '../snapshot/applicationClassTypeMetadata';
import { encodeProgramArtifacts, isBuiltinObjectTypeName } from '../../../src/peoplecode/encoder';
import { createApplicationClassTypeMetadataProvider } from '../../../src/peoplecode/applicationClassTypeMetadata';

function owner(def: any) {
  const values = [def.objectvalue1, def.objectvalue2, def.objectvalue3, def.objectvalue4, def.objectvalue5, def.objectvalue6, def.objectvalue7]
    .map((v: string) => (v ?? '').trim());
  const ids = [def.objectid1, def.objectid2, def.objectid3, def.objectid4, def.objectid5, def.objectid6, def.objectid7];
  const eventIndex = values.findIndex((v: string) => v.toLowerCase() === 'onexecute');
  const recordIndex = ids.findIndex(id => id === 1);
  const fieldIndex = ids.findIndex(id => id === 2);
  return {
    recordName: recordIndex >= 0 ? values[recordIndex] : values[0],
    fieldName: fieldIndex >= 0 ? values[fieldIndex] : values[1],
    packagePath: values.slice(0, eventIndex < 0 ? values.length : eventIndex).filter(Boolean)
  };
}

const db = openSnapshotDatabase();
const withProvider = process.argv.includes('--provider') || process.argv.includes('--diagnostics');
const provider = withProvider
  ? createApplicationClassTypeMetadataProvider(listSnapshotApplicationClassDefinitions(db), { isBuiltinType: isBuiltinObjectTypeName })
  : undefined;
const out: Record<number, { s: string[]; g: string[]; x: boolean; h: string; d: boolean; t: [number, number, number] }> = {};
for (const def of listSnapshotDefinitions(db) as any[]) {
  const rows = [...def.names].sort((a: any, b: any) => Number(a.namenum) - Number(b.namenum));
  const stored = rows
    .map((r: any) => String(r.recname ?? '').trim().toUpperCase() === 'PACKAGE' ? `PACKAGE.${String(r.refname ?? '').trim().toUpperCase()}` : 'o')
    .slice(1);
  const descriptive = rows.some((r: any) => String(r.recname ?? '').trim().toUpperCase() === 'PACKAGE' && String(r.packageroot ?? '').trim() !== '');
  const consulted: [number, number, number] = [0, 0, 0];
  try {
    const artifacts = encodeProgramArtifacts(def.sourceText, {
      owner: owner(def),
      applicationClassTypeMetadata: provider,
      applicationClassTypeMetadataDiagnosticsOnly: process.argv.includes('--diagnostics'),
      applicationClassTypeMetadataTrace: (e: any) => { consulted[e.result === undefined ? 2 : e.result.kind === 'class' ? 0 : 1]++; }
    } as any) as any;
    const generated = artifacts.references
      .map((r: any) => r.kind === 'package' ? `PACKAGE.${String(r.packageName ?? '').toUpperCase()}` : 'o')
      .slice(1);
    out[def.definitionId] = {
      s: stored, g: generated, x: artifacts.program.equals(def.storedProgram),
      h: createHash('sha1').update(artifacts.program).digest('hex'), d: descriptive, t: consulted
    };
  } catch {
    // unsupported syntax / encode error
  }
}
fs.writeFileSync(process.argv[2], JSON.stringify(out));
const values = Object.values(out);
const totals = values.reduce((acc, v) => acc.map((n, i) => n + v.t[i]) as [number, number, number], [0, 0, 0] as [number, number, number]);
console.log(`${values.length} encoded, ${values.filter(v => v.x).length} forward-exact; provider consultations: class ${totals[0]}, other type ${totals[1]}, unresolved ${totals[2]}`);
