/*
 * Cycle 78 Phase 1-4 (mandatory population extraction + byte-divergence
 * census, read-only, no encoder changes yet).
 *
 * Cycle 77 fixed a validator wiring defect (isApplicationClass never
 * passed to decodeProgram), which caused the DECODER_BARE_IDENTIFIER
 * taxonomy category to collapse from 1,344 to 26. This script
 * reconstructs the exact set of definitions that LEFT that old
 * DECODER_BARE_IDENTIFIER/DECODE_SOURCE_MISMATCH population (1,994
 * total under the pre-Cycle-77 taxonomy) but did NOT become EXACT and
 * did NOT remain DECODE_SOURCE_MISMATCH -- i.e. decode now succeeds and
 * matches source, but a separate, previously-invisible ENCODER-side (or
 * roundtrip-only) defect keeps them from EXACT. This is the "~1,042
 * newly exposed encoder-side population" Cycle 78's own brief refers
 * to.
 *
 * For each member, fetches full byte-level diff detail (first
 * differing offset, stored/generated byte windows, source context) via
 * direct validateDefinition + a local byte-window helper (the
 * taxonomy's own row schema does not carry storedDiffHex/
 * generatedDiffHex).
 *
 * Usage: npx tsx tools/corpus/research/cycle78-encoder-population-extract.ts
 */
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';

import { openSnapshotDatabase } from '../snapshot/store';
import { getSnapshotDefinition, snapshotToCorpusDefinition } from '../snapshot/reader';
import { validateDefinition } from '../validator';

// The pre-Cycle-77 taxonomy snapshot, read directly from git history so
// this script stays reproducible without depending on any local scratch
// file. c48f938 is Cycle 76's own commit (the last one before Cycle 77's
// isApplicationClass validator fix).
const OLD_TAXONOMY_REF = 'c48f938:.claude/nonexact-taxonomy.json';
const NEW_TAXONOMY_PATH =
  path.join(__dirname, '../../../.claude/nonexact-taxonomy.json');
const OUT_PATH =
  path.join(__dirname, '../../../.claude/cycle78-encoder-population.json');

function loadOldTaxonomy(): any {
  const json = execFileSync('git', ['show', OLD_TAXONOMY_REF], {
    cwd: path.join(__dirname, '../../..'),
    maxBuffer: 1024 * 1024 * 64
  }).toString('utf8');
  return JSON.parse(json);
}

function sourceWindow(source: string, offset: number, radius = 80): string {
  if (offset === undefined || offset < 0 || offset > source.length) return '';
  const start = Math.max(0, offset - radius);
  const end = Math.min(source.length, offset + radius);
  return source.slice(start, end).replace(/\r/g, '\\r').replace(/\n/g, '\\n').replace(/\t/g, '\\t');
}

async function main() {
  const oldData = loadOldTaxonomy();
  const oldIds: number[] = oldData.rows
    .filter((r: any) => r.primaryCategory === 'DECODER_BARE_IDENTIFIER' || r.primaryCategory === 'DECODE_SOURCE_MISMATCH')
    .map((r: any) => r.definitionId);

  const newData = JSON.parse(fs.readFileSync(NEW_TAXONOMY_PATH, 'utf8'));
  const newById = new Map<number, any>(newData.rows.map((r: any) => [r.definitionId, r]));

  console.log(`Old DECODER_BARE_IDENTIFIER + DECODE_SOURCE_MISMATCH population: ${oldIds.length}`);

  const stillDecodeBlocked: number[] = [];
  const newlyExact: number[] = [];
  const encoderPopulationIds: number[] = [];

  for (const id of oldIds) {
    const row = newById.get(id);
    if (!row) {
      newlyExact.push(id);
    } else if (row.classification === 'DECODE_SOURCE_MISMATCH') {
      stillDecodeBlocked.push(id);
    } else {
      encoderPopulationIds.push(id);
    }
  }

  console.log(`Newly EXACT: ${newlyExact.length}`);
  console.log(`Still decode-blocked (DECODE_SOURCE_MISMATCH): ${stillDecodeBlocked.length}`);
  console.log(`Newly exposed encoder-side population: ${encoderPopulationIds.length}`);

  const db = openSnapshotDatabase();
  const rows: any[] = [];

  for (const id of encoderPopulationIds) {
    const snap = getSnapshotDefinition(db, id);
    const capture = {
      definition: snapshotToCorpusDefinition(snap, 0),
      sourceRows: 1, source: snap.sourceText,
      programRows: 1, program: snap.storedProgram,
      names: snap.names.map(row => ({
        NAMENUM: row.namenum, RECNAME: row.recname, REFNAME: row.refname,
        PACKAGEROOT: row.packageroot, QUALIFYPATH: row.qualifypath, APPCLASSMETHOD: row.appclassmethod
      }))
    };

    const result: any = await validateDefinition(capture as any);
    const taxRow = newById.get(id);

    const offset = result.firstDiffOffset;
    const sourceCtx = typeof offset === 'number' ? sourceWindow(snap.sourceText, offset) : '';

    rows.push({
      definitionId: id,
      objectid1: snap.objectid1,
      appClass: snap.objectid1 === 104,
      classification: result.classification,
      primaryCategory: taxRow?.primaryCategory,
      sourceEncodeExact: result.sourceEncodeExact,
      roundtripExact: result.roundtripExact,
      storedProgramBytes: result.storedProgramBytes,
      generatedProgramBytes: result.generatedProgramBytes,
      lengthDelta: (result.generatedProgramBytes ?? 0) - result.storedProgramBytes,
      firstDiffOffset: offset,
      storedDiffHex: result.storedDiffHex ?? '',
      generatedDiffHex: result.generatedDiffHex ?? '',
      sourceContext: sourceCtx,
      errorMessage: result.errorMessage,
      construct: result.construct
    });
  }

  fs.writeFileSync(OUT_PATH, JSON.stringify({
    generatedAt: new Date().toISOString(),
    oldPopulation: oldIds.length,
    newlyExact: newlyExact.length,
    stillDecodeBlocked: stillDecodeBlocked.length,
    encoderPopulation: encoderPopulationIds.length,
    newlyExactIds: newlyExact,
    stillDecodeBlockedIds: stillDecodeBlocked,
    rows
  }, null, 2));

  console.log(`\nWrote ${OUT_PATH}`);

  // Quick breakdown by whether sourceEncode itself is exact
  const sourceEncodeFail = rows.filter(r => !r.sourceEncodeExact).length;
  const roundtripOnlyFail = rows.filter(r => r.sourceEncodeExact && !r.roundtripExact).length;
  console.log(`sourceEncode not exact: ${sourceEncodeFail}`);
  console.log(`sourceEncode exact but roundtrip not: ${roundtripOnlyFail}`);

  const appClassCount = rows.filter(r => r.appClass).length;
  console.log(`App Class (objectid1=104): ${appClassCount} / ordinary: ${rows.length - appClassCount}`);
}

main();
