/*
 * Cycle 91: top-level Local declarations AFTER executable code (research
 * only). For every non-App-Class program, split stored and generated bytes
 * into top-level items (Cycle 85 splitter) and, for every top-level Local
 * item after the first executable statement, compare the layout bytes after
 * it (stored vs generated) and record what follows it.
 *
 * Usage: npx tsx tools/corpus/research/cycle91-post-executable-local-census.ts
 */
import { openSnapshotDatabase } from '../snapshot/store';
import { listSnapshotDefinitions } from '../snapshot/reader';
import { encodeProgramArtifacts } from '../../../src/peoplecode/encoder';
import { NameTable } from '../../../src/peoplecode/progtext';
import { topLevelItems } from './cycle85-function-continuity-census';

const tally = new Map<string, number[]>();
let programs = 0;
for (const def of listSnapshotDefinitions(openSnapshotDatabase()) as any[]) {
  if (def.objectid1 === 104) continue;
  const storedNames = new NameTable();
  for (const r of def.names) storedNames.add(Number(r.namenum), 'x');
  let stored: any[];
  let generated: any[];
  try {
    stored = topLevelItems(def.storedProgram, storedNames, false);
    const artifacts = encodeProgramArtifacts(def.sourceText, {
      owner: { recordName: def.objectvalue1.trim(), fieldName: def.objectvalue2.trim() }
    } as any);
    const generatedNames = new NameTable();
    for (const r of artifacts.references) generatedNames.add(r.sequence, 'x');
    generated = topLevelItems(artifacts.program, generatedNames, false);
  } catch { continue; }
  const firstX = stored.findIndex(i => i.kind === 'X');
  if (firstX < 0) continue;
  const post = stored.map((item, index) => ({ item, index })).filter(({ item, index }) => index > firstX && item.kind.startsWith('L'));
  if (!post.length) continue;
  programs++;
  const aligned = generated.length === stored.length && generated.every((g, i) => g.kind === stored[i].kind);
  for (const { item, index } of post) {
    const next = stored[index + 1]?.kind ?? 'EOF';
    const s = item.layoutAfter.trim() || '-';
    const g = aligned ? (generated[index].layoutAfter.trim() || '-') : '(unaligned)';
    const key = `${item.kind.padEnd(2)} next=${next.padEnd(3)} stored=[${s}] generated=[${g}] ${s === g ? 'match' : 'MISMATCH'}`;
    (tally.get(key) ?? tally.set(key, []).get(key)!).push(def.definitionId);
  }
}
console.log(`programs with a top-level Local after executable code: ${programs}`);
for (const [key, ids] of [...tally].sort((a, b) => b[1].length - a[1].length)) {
  console.log(String(ids.length).padStart(5), key, [...new Set(ids)].slice(0, 6).join(','));
}
